name: atena_app
description: "ATENA: vacantes y trámites escolares entre familias e instituciones educativas."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  # Fuente de íconos que usan los controles de estilo iOS del framework.
  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.3
  pdf: ^3.13.1
  printing: ^5.15.1
  image_picker: ^1.2.3
  share_plus: ^13.3.1
  file_picker: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cinzel-Bold.ttf
          weight: 700

  assets:
    - assets/brand/
